### ISSUE TITLE
Coordinate future updates to simulator

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/www_simulator#1]
Since the farming community is looking at the simulator to gauge their potential returns, any updates that change the rewards shown are important to communicate with clear reasoning to avoid confusion. Today, we saw negative reactions from the community after the SU reward rate was corrected from 1.5 to 1.

In the future, I propose coordinating any changes to the simulator with both the farming team (@andhartl) and the communications team (@Sacha96, @samtaggart, or myself). This way, changes can be reviewed for correctness, and communication can be prepared for our channels before the change goes live.

**Comment by samtaggart** [comment]
100% these types of things need to be communicated.
